version: '3'
services:
  api:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
      - grafana

  prometheus:
    image: prom/prometheus:v2.37.1
    command: --web.enable-lifecycle --config.file=/etc/prometheus/config.yml
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/config.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:8.5.2
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning

    ports:
      - "3000:3000"

volumes:
  grafana_data: {}
